package cz.cvut.copakond.pinkfluffyunicorn.model.data;

import java.io.IOException;

import cz.cvut.copakond.pinkfluffyunicorn.model.utils.enums.ErrorMsgsEnum;
import org.json.JSONArray;
import org.json.JSONObject;
import org.json.JSONException;
import java.nio.file.Files;
import java.nio.file.Paths;

public class JsonFileManager {
    public static JSONObject readJsonFromFile(String filePath) {
        try {
            String content = new String(Files.readAllBytes(Paths.get(filePath)));
            return new JSONObject(content);
        } catch (IOException e) {
           ErrorMsgsEnum.LOAD_JSON_FILE.getValue(filePath, e);
        } catch (JSONException e) {
            ErrorMsgsEnum.LOAD_JSON_PARSE.getValue(filePath, e);
        }
        return null;
    }

    public static boolean writeJsonToFile(String filePath, JSONObject data) {
        try {
            // Convert the JSONObject to a formatted string with custom list formatting
            String jsonString = formatJson(data, 0);

            // Write the formatted JSON string to the file
            Files.write(Paths.get(filePath), jsonString.getBytes());
            return true;
        } catch (IOException e) {
            ErrorMsgsEnum.SAVE_JSON_FILE.getValue(filePath, e);
        }
        return false;
    }

    // Method to format JSON with custom list formatting, the inner lists are in one line, generated by AI
    private static String formatJson(Object obj, int indent) {
        StringBuilder sb = new StringBuilder();
        String indentStr = "  ".repeat(indent);  // Indentation using spaces

        if (obj instanceof JSONObject) {
            JSONObject json = (JSONObject) obj;
            sb.append("{\n");
            int count = 0;
            for (String key : json.keySet()) {
                if (count++ > 0) sb.append(",\n");
                sb.append(indentStr).append("  \"").append(key).append("\": ");
                sb.append(formatJson(json.get(key), indent + 1));
            }
            sb.append("\n").append(indentStr).append("}");
        }
        else if (obj instanceof JSONArray) {
            JSONArray arr = (JSONArray) obj;

            // Check if it's a list of lists that should be in one line
            boolean isInnerList = arr.length() > 0 && arr.get(0) instanceof JSONArray;

            if (isInnerList) {
                sb.append("[\n");
                for (int i = 0; i < arr.length(); i++) {
                    if (i > 0) sb.append(",\n");
                    sb.append(indentStr).append("  ").append(arr.get(i).toString()); // Keep inner lists in one line
                }
                sb.append("\n").append(indentStr).append("]");
            } else {
                sb.append(arr.toString()); // Normal JSON array formatting
            }
        }
        else if (obj instanceof String) {
            sb.append("\"").append(obj).append("\"");
        }
        else {
            sb.append(obj);
        }

        return sb.toString();
    }
}
